#!/usr/bin/env python3
"""
Example script showing how ba.agent can use the enhanced jira_analyst.py
"""

from jira_analyst import JiraAnalyst
import json


def ba_workflow_example(issue_key):
    """
    Example workflow for BA agent to:
    1. Read a JIRA issue
    2. Perform analysis
    3. Update the issue with analysis
    """
    
    # Initialize JIRA analyst
    analyst = JiraAnalyst()
    
    # Step 1: Read the JIRA issue
    print(f"Step 1: Reading issue {issue_key}...")
    issue_data = analyst.get_issue(issue_key)
    
    print(f"\nIssue Summary: {issue_data['summary']}")
    print(f"Description: {issue_data['description'][:200]}...")
    
    # Step 2: Generate business analysis (mock example)
    print(f"\nStep 2: Generating business analysis...")
    
    analysis = f"""
## Business Analysis for {issue_key}

### Business Assumptions:
1. **Assumption:** Users must be authenticated before accessing this feature.
   **Impact:** Unauthenticated users will be redirected to login page.

2. **Assumption:** System operates during business hours (9 AM - 5 PM EST).
   **Impact:** After-hours requests are queued for next business day.

3. **Assumption:** Data validation occurs on both client and server side.
   **Impact:** Enhanced security but may increase latency.

4. **Assumption:** API rate limiting is 100 requests per minute per user.
   **Impact:** Heavy users may experience throttling.

5. **Assumption:** All monetary values are in USD unless specified.
   **Impact:** Currency conversion not supported in initial release.

### Key Requirements Identified:
- User authentication required
- Input validation on all fields
- Error handling for edge cases
- Performance optimization for large datasets

### Edge Cases to Consider:
- Empty input validation
- Concurrent user access
- Network timeout handling
- Database connection failures

### Recommended Test Scenarios:
- Happy path with valid data
- Invalid input validation
- Boundary conditions
- Concurrent user scenarios
- Performance under load

### Feature File Location:
Will be created at: `features/{issue_key}-{feature_name}.feature`

---
*Analysis generated by BA Agent*
"""
    
    # Step 3: Update JIRA with the analysis
    print(f"\nStep 3: Updating JIRA issue with analysis...")
    result = analyst.update_issue_with_analysis(
        issue_key, 
        analysis,
        comment_prefix="🔍 BA Analysis Complete"
    )
    
    if result['success']:
        print(f"\n✅ Successfully updated {issue_key}")
        print(f"   Message: {result['message']}")
    else:
        print(f"\n❌ Failed to update {issue_key}")
        print(f"   Error: {result['error']}")
    
    return issue_data, analysis


def main():
    """Main entry point for example"""
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python ba_agent_example.py <ISSUE_KEY>")
        print("Example: python ba_agent_example.py PROJ-123")
        sys.exit(1)
    
    issue_key = sys.argv[1]
    
    try:
        issue_data, analysis = ba_workflow_example(issue_key)
        print("\n" + "="*80)
        print("BA Workflow Complete!")
        print("="*80)
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
